In [1]:
import numpy as np
from TensorNetworks import *

In [2]:
qc = MPS(3, 3)

cx = MPS.MultiGates["CX"]
h = MPS.SingleGates["H"]
q = qc.tensors[1]

In [3]:
qc.initialize((0,1,0))
qc

QuantumCircuit(3)

[[[1.+0.j]]

 [[0.+0.j]]]


[[[0.+0.j]]

 [[1.+0.j]]]


[[[1.+0.j]]

 [[0.+0.j]]]


In [4]:
MPS.createControlledUnitary("Y")

array([[[[ 0.+0.j, -0.-1.j],
         [ 0.+0.j,  0.+0.j]],

        [[ 0.+1.j,  0.+0.j],
         [ 0.+0.j,  0.+0.j]]],


       [[[ 0.+0.j,  0.+0.j],
         [ 1.+0.j,  0.+0.j]],

        [[ 0.+0.j,  0.+0.j],
         [ 0.+0.j,  1.+0.j]]]])

In [5]:
MPS.SingleGates.keys()

dict_keys(['X', 'Y', 'Z', 'H'])

In [6]:
MPS.MultiGates.keys()

dict_keys(['CX', 'SWAP', 'CY'])

In [7]:
sin = np.sin
cos = np.cos

In [8]:
cos

<ufunc 'cos'>

In [9]:
cos(0)

1.0

In [10]:
def gate():
    return 55

gate()

55

In [11]:
d = {}
d

{}

In [12]:
d[5] = gate()

In [13]:
d[5]

55

In [14]:
qc

QuantumCircuit(3)

[[[1.+0.j]]

 [[0.+0.j]]]


[[[0.+0.j]]

 [[1.+0.j]]]


[[[1.+0.j]]

 [[0.+0.j]]]


In [15]:
qc.n_qubits

3

In [16]:
qc = [q, q, q]

In [17]:
q

array([[[1.+0.j]],

       [[0.+0.j]]])

In [18]:
qc

[array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[1.+0.j]],
 
        [[0.+0.j]]])]

In [19]:
Operations = ["X", "Y", "Z", "H", "RX", "RY", "RZ"]
ControlledOps = ["C"+op for op in Operations]

In [20]:
ControlledOps

['CX', 'CY', 'CZ', 'CH', 'CRX', 'CRY', 'CRZ']

In [21]:
"CRX" in Operations + ControlledOps

True