In [1]:
import numpy as np
from TensorNetworks import *

In [2]:
qc = MPS(3, 3)

cx = MPS.MultiGates["CX"]
h = MPS.SingleGates["H"]
q = qc.tensors[1]

In [3]:
qc.initialize((0,1,0))
qc

QuantumCircuit(3)

[[[1.+0.j]]

 [[0.+0.j]]]


[[[0.+0.j]]

 [[1.+0.j]]]


[[[1.+0.j]]

 [[0.+0.j]]]


In [11]:
M_c, M_t = qc[0], qc[1]
M_c, M_t, M_c.shape

(array([[[1.+0.j]],
 
        [[0.+0.j]]]),
 array([[[0.+0.j]],
 
        [[1.+0.j]]]),
 (2, 1, 1))

In [12]:
T1 = np.einsum("ijk, lkm -> ijlm", M_c, M_t)
T1, T1.shape

(array([[[[0.+0.j],
          [1.+0.j]]],
 
 
        [[[0.+0.j],
          [0.+0.j]]]]),
 (2, 1, 2, 1))

In [15]:
T2 = np.einsum("klij, ijmn -> klmn", cx, T1)
T2, T2.shape

(array([[[[0.+0.j],
          [1.+0.j]],
 
         [[0.+0.j],
          [1.+0.j]]],
 
 
        [[[0.+0.j],
          [0.+0.j]],
 
         [[0.+0.j],
          [0.+0.j]]]]),
 (2, 2, 2, 1))

In [28]:
U, S, V = np.linalg.svd(T2)

In [29]:
U, U.shape

(array([[[[ 0.+0.j, -1.+0.j],
          [ 1.+0.j,  0.+0.j]],
 
         [[ 0.+0.j, -1.+0.j],
          [ 1.+0.j,  0.+0.j]]],
 
 
        [[[ 1.+0.j,  0.+0.j],
          [ 0.+0.j,  1.+0.j]],
 
         [[ 1.+0.j,  0.+0.j],
          [ 0.+0.j,  1.+0.j]]]]),
 (2, 2, 2, 2))

In [30]:
S, S.shape

(array([[[1.],
         [1.]],
 
        [[0.],
         [0.]]]),
 (2, 2, 1))

In [44]:
M1 = np.einsum("ijkl, klm -> ijl", U, S)
M1, M1.shape

(array([[[ 0.+0.j, -1.+0.j],
         [ 0.+0.j, -1.+0.j]],
 
        [[ 1.+0.j,  0.+0.j],
         [ 1.+0.j,  0.+0.j]]]),
 (2, 2, 2))